### ISSUE TITLE
How to create board definition using meta-kiss

### ISSUE THREAD

**Issue by radoslavp** [bootlin/simplest-yocto-setup#5]
Thanks for creating this! Seems to be really promising for our purposes. But still, i'm bit unsure how to use it properly, or rather how to create new board definition using meta-kiss as a reference.

This is what i did:
* made a copy of meta-kiss and renamed everything that referenced meta-kiss, stompduck or dogbonedark
* built image and run it on dk1 board and everything went smoothly
* created a patch that creates a dts file for our board (for now, it's just a copy of dk1 dts); added it to recipes-bsp/u-boot/u-boot-xxx/stm32mp1/
* created a patch that adds our board's dts file to Makefile; added it also to recipes-bsp/u-boot/u-boot-xxx/stm32mp1/
* added paths to these patches to recipes-bsp/u-boot/u-boot-xxx_git.bb using SRC_URI:append:stm32mp1 = " file://....dts.patch"
* also renamed all mentions of dk1 dtb file in conf/machine/our_board.conf 
* now when i build the image, it fails on binman: Device tree 'u-boot.dtb' does not have a 'binman' node

Is this correct way to do it? Thank you.

**Comment by radoslavp** [comment]
Ok, figured the binman issue out (had to also create a patch to add stm32mp157a-board-u-boot.dtsi which defines binman node).

But still would appreciate some comments on whether the way i went is a good one. Thank you.

**Comment by lucaceresoli** [comment]
Hi @radoslavp, thanks for your appreciation!

Using your own device tree for U-Boot should be easier than how you are doing it now.
First you can write a very simple recipe that builds your device tree, which is very easy using the [devicetree](https://docs.yoctoproject.org/ref-manual/classes.html#devicetree) bbclass. The class also ensures your recipe provides the `virtual/dtb` virtual package.

Then you can have your U-Boot recipe depend on `virtual/dtb` and ask the U-Boot Makefile to use your own DTB file using the EXT_DTB environment variable. See [the U-Boot documentation](https://docs.u-boot.org/en/latest/develop/devicetree/control.html#configuration) for more details.

Actually we have a plan to add all of this to meta-kiss. Stay tuned on #3 to see when it will be done.

**Comment by radoslavp** [comment]
Thanks. Sorry for late reply - got sidetracked. Tried this out and it was pretty easy. For anybody interested, short howto (writing it from top of my head, so hope it's complete - anybody feel free to correct me):
* create directory under recipes-bsp, for example recipes-bsp/device-tree
* create recipe file, for example recipes-bsp/device-tree/device-tree.bb with following content (change anything inside <>):
```
SUMMARY = "<Some summary>"
DESCRIPTION = "<Some description>"
SECTION = "bsp"

LICENSE = "<your license name>"

inherit devicetree

PROVIDES = "virtual/dtb"

COMPATIBLE_MACHINE:<machine-name> = ".*"
SRC_URI:append:<machine-name> = " \
        file://<device tree name>.dts \
        "
```
* create subdirectory recipes-bsp/device-tree/files
* put your dts/dtsi files to recipes-bsp/device-tree/files
* in conf/machine/<machine-name>.conf change line `UBOOT_MAKE_TARGET:append = " DEVICE_TREE=<device tree name>"` to `UBOOT_MAKE_TARGET:append = " EXT_DTB=boot/devicetree/<device tree name>.dtb"`
*  build

I used this recipe file as a template: https://github.com/nathanrossi/meta-xilinx/blob/nrossi/devicetree-classify/meta-xilinx-bsp/recipes-bsp/device-tree/device-tree.bb

**Comment by radoslavp** [comment]
Well, the previous post seems to be premature. The device-tree recipe seems to build correctly, but after clean u-boot rebuild it fails on:
```
Device Tree Source (boot/device_tree_name.dtb) is not correctly specified.
| Please define 'CONFIG_DEFAULT_DEVICE_TREE'
| or build with 'DEVICE_TREE=<device_tree>' argument
```
Originally, i had something like this in my machine conf: UBOOT_MAKE_TARGET:append = " EXT_DTB=boot/devicetree/device_tree_name.dtb" - i don't know where i got the 'boot/devicetree' path :), but even when changing it to just boot/device_tree_name.dtb (as it is in the link to u-boot documentation, you provided), it still fails. I'm not sure what path should i use.

The other thing i'm not sure about is what having 'U-Boot recipe depend on virtual/dtb' actually means - is it adding DEPENDS:append:stm32mp1 = "virtual/dtb" to u-boot recipe? Cause that didn't help.

In case, you're working on this and there is gonna be a commit adding this in the near future, i'll wait. If not, i'll be grateful for any help regarding this. Thank you.

**Comment by radoslavp** [comment]
Just na update in case, somebody needs it. The correct path in EXT_DTB seems to be ../recipe-sysroot/boot/devicetree/device-tree-name.dtb" - at least that's what worked for me.

But then, there popped up another problem - u-boot Makefile somehow automatically includes <device-tree-name>-u-boot.dtsi which adds changes on top of original dts file used to build dtb for linux (as discussed here: https://wiki.st.com/stm32mpu/index.php?title=U-Boot_overview&oldid=79536#Device_tree). It doesn't seem devicetree.bbclass does this, so i just tried to include it in the dts, but this dtsi includes some header files present in u-boot sources, but not present in kernel sources (which devicetree.bbclass sources when building the device tree) - namely dt-bindings/clock/stm32mp1-clksrc.h. Looked at devicetree.bbclass, but wasn't sure how to tell it to use u-boot sources instead of kernel ones. So that's where i stopped for now.
